{% set version = "0.4.2" %}

package:
  name: missingno
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/missingno/missingno-{{ version }}.tar.gz
  sha256: 02eb92085e4efa0d4c06239750ac44a8d6cc5979bf5b954a09c47b648413ff41

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - pandas
    - matplotlib-base
    - seaborn

test:
  imports:
    - missingno

about:
  home: https://github.com/ResidentMario/missingno
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Missing data visualization module for Python.'

extra:
  recipe-maintainers:
    - vasudevanv
    - ericmjl
