{% set version = "0.5.1" %}

package:
  name: missingno
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/missingno/missingno-{{ version }}.tar.gz
  sha256: 22e1735a9213df7425e76123ebcc627d11a2608a1d725b90c6a2d7329db718db

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - pandas
    - matplotlib-base
    - seaborn

test:
  imports:
    - missingno

about:
  home: https://github.com/ResidentMario/missingno
  license: MIT
  license_family: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Missing data visualization module for Python.

extra:
  recipe-maintainers:
    - ericmjl
